### ISSUE TITLE
Error in `kendall_tau` function with NaN values

### ISSUE THREAD

**Issue by 3pwvej** [TY-Cheng/torchvinecopulib#30]
Hello,

Thank you for the work done on this package; it's been very helpful. I've been running into an issue when fitting vines on my data that I believe has to do with the presence of `NaN` values and the `kendalltau` function:

```markdown
def kendall_tau(
    x: torch.Tensor,
    y: torch.Tensor,
    tau_min: float = _TAU_MIN,
    tau_max: float = _TAU_MAX,
) -> float:
    """x, y are both of shape (n, 1)"""
    res = kendalltau(x.cpu().ravel(), y.cpu().ravel())
    return (
        max(min(res.correlation.item(), tau_max), tau_min),
        res.pvalue.item(),
    )
```

When I have nan values in my data tensor, the function throws the following error:
```
AttributeError: 'float' object has no attribute 'item'
```

It seems that setting the `nan_policy` parameter in the `scipy.stats.kendalltau` function to `'omit'` resolves the issue. Would it be possible to incorporate this change or add an option to set the `nan_policy` parameter? Thanks!

**Comment by TY-Cheng** [comment]
Hello,


Thank you for your feedback and for using our package! We’re glad to hear it has been helpful.

The issue you’re encountering arises because the default behavior of `scipy.stats.kendalltau` is `nan_policy='propagate'`. Under this setting, the presence of `NaN` values will result in a `NaN` return value, leading to the error you’ve seen. The propagate policy encourages users to handle missing data explicitly, ensuring the integrity of statistical analyses.

For the same reason, we nudge you to be aware what are being given into vine part. If you prefer to omit `NaN` values, you can do so explicitly before fitting the vine model. For example on a tensor `V_mvcp` with `NaN`:

```python
V_mvcp = V_mvcp[~V_mvcp.isnan().any(axis=1)]
```

We appreciate your suggestion and will address this in docs in a future release.
Thank you again for bringing this to our attention!

**Comment by 3pwvej** [comment]
Hello, 

Thank you for the quick and thoughtful response! We appreciate the clarification and the importance of explicitly handling missing data.

We do try to be mindful of `NaN` values and address them when we can. However, in our case, we intentionally leave in certain `NaN` values because filtering out rows entirely would result in losing observations where only some columns have missing data. Our aim is to retain as many rows as possible, as those with partial missingness still provide valuable information.

Thank you for considering this issue in the documentation. It would be great if an option to specify this behavior is added in the future, but it’s no problem if it’s not a priority since we can handle it on our end.
